'use strict';
(() => {
 const R=Retainer;
 const fixture=async body=>{const z=new JSZip();z.file('word/document.xml',`<w:document xmlns:w="${R.W}"><w:body>${body}</w:body></w:document>`);return z.generateAsync({type:'uint8array'});};
 const p=s=>`<w:p><w:r><w:t xml:space="preserve">${R.escape(s)}</w:t></w:r></w:p>`;
 R.fixture=fixture;
 R.selftest=async()=>{
  const checks=[],test=async(name,fn)=>{try{await fn();checks.push({name,passed:true});}catch(e){checks.push({name,passed:false,error:e.message});}},eq=(a,b)=>R.assert(a===b,`${String(a)} ≠ ${String(b)}`),reject=async fn=>{let failed=false;try{await fn();}catch{failed=true;}R.assert(failed,'反例未被拦截');};
  await test('金额正例：小数万元、大额、角分',()=>{eq(R.money('2.5万元').upfront,'贰万伍仟元整');eq(R.money('100001元').upfront,'壹拾万零壹元整');eq(R.money('1,234.56元').upfront,'壹仟贰佰叁拾肆元伍角陆分');eq(R.money('0.05').upfront,'零元伍分');eq(R.money('100000001').upfront,'壹亿零壹元整');});
  await test('中文与全角百分比',()=>{for(const s of ['前期2万+12.5%','前期2万+百分之十二点五','前期2万+12.5％'])eq(R.parseFee(s,'semi_risk').risk_rate,'百分之十二点五（12.5%）');});
  await test('金额反例：负值、分期、比例缺金额、错误分隔',async()=>{for(const [s,t]of [['5%','semi_risk'],['3万+5万结果','fixed'],['-5元','fixed'],['1,23元','fixed'],['0.001','fixed'],['50000+风险','semi_risk'],['50000+101%','semi_risk'],['50000+5%','fixed']])await reject(()=>R.parseFee(s,t));});
  const input={case_type:'民商事',party_type:'个人',plaintiff:'测试张三&A',defendant:'测试李四<乙>',cause:'买卖合同纠纷',fee_desc:'25000元',fee_type:'固定',stage:'一审、二审',court:'测试人民法院',legal_rep:'测试王五',legal_rep_position:'经理'};
  await test('分类识别与民事纠纷例外',()=>{eq(R.normalize({...input,case_type:'自动识别',cause:'侵犯著作权纠纷'}).case_type,'civil');eq(R.normalize({...input,case_type:'自动识别',cause:'集资诈骗',stage:'一审'}).case_type,'criminal');eq(R.normalize({...input,party_type:'自动识别',plaintiff:'张行'}).party_type,'individual');});
  await test('三类主体模板完整生成及字段校验（13份）',async()=>{let counted=0;for(const group of ['个人委托','公司委托','刑事']){const n=R.normalize({...input,case_type:group==='刑事'?'刑事':'民商事',party_type:group.startsWith('公司')?'公司':'个人',cause:group==='刑事'?'集资诈骗':input.cause,fee_type:'固定',fee_desc:'25000元'}),ts=RETAINER_BUILTIN.templates.filter(t=>t.group===group),out=await R.generate(n,ts);counted+=ts.length;for(const f of out.files)R.assert(!(await R.inspectDoc(f.bytes)).fields.length,'残留字段');}eq(counted,13);});
  await test('三种收费模式注入合同第六条',async()=>{const combos=[['固定','25000元','固定收费模式'],['半风险','前期2万+12.5%','半风险代理收费模式'],['全风险','回款额的15%','全风险代理收费模式']];for(const [ft,fd,mark] of combos){const n=R.normalize({...input,fee_type:ft,fee_desc:fd}),contract=RETAINER_BUILTIN.templates.find(t=>t.group==='个人委托'&&t.tag==='contract'),out=await R.generate(n,[contract]),text=(await R.inspectDoc(out.files[0].bytes)).text;R.assert(!text.includes('{{'),'残留占位符：'+ft);R.assert(text.includes('甲乙双方协商确定'),'未注入收费条款：'+ft);R.assert(text.includes(mark),'收费模式标识不符：'+ft);}});
  await test('完整民事与刑事目录及归档内容',async()=>{for(const ct of ['民商事','刑事']){const n=R.normalize({...input,case_type:ct,cause:ct==='刑事'?'盗窃':input.cause}),out=await R.generate(n,RETAINER_BUILTIN.templates.filter(t=>t.group===n.group)),z=await R.openZip(await R.caseZip(out,true));for(const d of R.config.directories[n.case_type])R.assert(z.files[n.caseName+'/'+d+'/'],'目录缺失：'+d);for(const f of out.files)eq(await R.hash(await z.file(n.caseName+'/01委托手续/'+f.name).async('uint8array')),await R.hash(f.bytes));}});
  await test('跨片段占位符与 XML 特殊字符',async()=>{const b=await fixture('<w:p><w:r><w:rPr><w:b/></w:rPr><w:t>前{{PLA</w:t></w:r><w:r><w:rPr><w:i/></w:rPr><w:t>INTIFF}}后</w:t></w:r></w:p>'),out=await R.transformDoc(b,p=>R.replaceInPara(p,{'{{PLAINTIFF}}':'A&B<甲>'}));eq((await R.inspectDoc(out.bytes)).text,'前A&B<甲>后');const z=await R.openZip(out.bytes),d=R.xml(await z.file('word/document.xml').async('string'));eq(R.els(d,'b').length,1);eq(R.els(d,'i').length,1);});
  await test('正文、表格、页眉、文本框占位符',async()=>{const z=new JSZip();z.file('word/document.xml',`<w:document xmlns:w="${R.W}"><w:body><w:tbl><w:tr><w:tc>${p('{{PLAINTIFF}}')}</w:tc></w:tr></w:tbl><w:p><w:r><w:pict><w:txbxContent>${p('{{DEFENDANT}}')}</w:txbxContent></w:pict></w:r></w:p></w:body></w:document>`);z.file('word/header1.xml',`<w:hdr xmlns:w="${R.W}">${p('{{YEAR}}')}</w:hdr>`);const out=await R.transformDoc(await z.generateAsync({type:'uint8array'}),p=>R.replaceInPara(p,{'{{PLAINTIFF}}':'甲','{{DEFENDANT}}':'乙','{{YEAR}}':'2030'}));const t=await R.inspectDoc(out.bytes);eq(t.fields.length,0);R.assert(t.text.includes('甲')&&t.text.includes('乙')&&t.text.includes('2030'),'字段缺失');});
  await test('清理保留颜色、字体与分页符',async()=>{const b=await fixture('<w:p><w:r><w:rPr><w:b/></w:rPr><w:t>A</w:t></w:r><w:r><w:rPr><w:b/></w:rPr><w:t>B</w:t></w:r><w:r><w:rPr><w:color w:val="FF0000"/></w:rPr><w:t>C</w:t></w:r><w:r><w:br w:type="page"/></w:r></w:p>'),out=await R.clean(b),z=await R.openZip(out.bytes),d=R.xml(await z.file('word/document.xml').async('string'));eq(R.els(d,'r').length,3);eq(R.els(d,'br').length,1);eq(R.els(d,'color')[0].getAttributeNS(R.W,'val'),'FF0000');});
  await test('注入引擎五种规则与未匹配保留',()=>{for(const mode of ['exact','regex_replace','blank_prefix','blank_suffix','underline_after_prefix']){const source=mode==='exact'||mode==='regex_replace'?'前张三后':mode==='underline_after_prefix'?'前张三后':'前   后';const d=R.xml(`<w:document xmlns:w="${R.W}"><w:p><w:r><w:rPr><w:u w:val="single"/></w:rPr><w:t>${source}</w:t></w:r></w:p></w:document>`),para=R.els(d,'p')[0],rule={mode,context:'前',old:'张三',pattern:'张三',prefix:'前',suffix:'后',new:'{{PLAINTIFF}}'};R.assert(R.applyRule(para,rule),'未命中：'+mode);eq(R.ptext(para),'前{{PLAINTIFF}}后');}});
  await test('源模板重建与未知字段拦截',async()=>{const b=await fixture(p('委 托 方：中科迈航信息技术有限公司')),out=await R.inject(b,'公司委托','auth');R.assert((await R.inspectDoc(out.bytes)).fields.includes('PLAINTIFF'),'未注入委托方');const bad=await fixture(p('{{UNKNOWN}}')),badHash=await R.hash(bad);await reject(()=>R.validateTemplate({id:'x',name:'x.docx',group:'个人委托',tag:'extra',base64:R.base64(bad),sha256:badHash}));});
  await test('收费条款转换及旧条款清除',async()=>{const b=await fixture(p('六、经双方商定，本合同律师费约定如下：')+p('（1）前期费用：旧条款')+p('（2）风险费用：旧条款')+p('七、其他条款')),out=await R.swapFee(b,'fixed'),info=await R.inspectDoc(out.bytes);R.assert(info.text.includes('UPFRONT_FEE')&&!info.text.includes('旧条款')&&info.text.includes('七、其他条款'),'收费转换错误');await reject(()=>R.swapFee(awaitless(),'fixed'));function awaitless(){return new Uint8Array();}});
  await test('标准 Excel 创建与读取',async()=>{const w=await R.readXlsx(await R.standardXlsx());eq(w.sheets.length,3);eq(w.sheets[0].rows[0][2].value,'委托方');const m=R.autoMapping(w.sheets[2].rows[0].map(c=>c.value)),rows=R.mapRows(w.sheets[2],0,m.mapping);eq(rows.length,3);eq(rows[0].row.fee_desc,'25000');});
  await test('自有 Excel 别名、乱序、前导零和重复映射',async()=>{const w=await R.readXlsx(await R.makeXlsx([{name:'自有表',rows:[['费用','甲方','阶段','被告','案由'],[25000,'00123','一审','乙方','合同纠纷']]}])),m=R.autoMapping(w.sheets[0].rows[0].map(c=>c.value)),rows=R.mapRows(w.sheets[0],0,m.mapping);eq(rows[0].row.plaintiff,'00123');R.assert(R.autoMapping(['甲方','委托方']).conflicts.length,'重复表头未报告');await reject(()=>R.mapRows(w.sheets[0],0,{plaintiff:1,defendant:1}));});
  await test('Excel 公式和错误值标记',()=>{const rows=R.mapRows({rows:[[],[{value:'公式',formula:true,ref:'A2'},{value:'#REF!',error:true,ref:'B2'}]]},0,{plaintiff:0,defendant:1});eq(rows[0].issues.length,2);});
  await test('资源包与工作包校验及损坏拦截',async()=>{const work={records:[{row:input}],index:0},b=await R.pack('work',work),p=await R.unpack(b,'work');eq(p.state.records[0].row.plaintiff,input.plaintiff);await R.unpack(await R.pack('resources'),'resources');const z=await R.openZip(b);z.file('payload.json','{}');await reject(()=>z.generateAsync({type:'uint8array'}).then(b=>R.unpack(b,'work')));});
  await test('版本漂移与目录穿越拦截',async()=>{const c=R.clone(R.config);c.version='99.0';await reject(()=>R.validateConfig(c,R.rules));const d=R.clone(R.config);d.directories.civil.push('../bad');await reject(()=>R.validateConfig(d,R.rules));eq(R.safeName('../../bad:case'),'_.._bad_case');});
  await test('导入文件外部资源、宏和实体阻断',async()=>{const b=await fixture(p('x')),z=await R.openZip(b);z.file('word/_rels/document.xml.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="x" TargetMode="External" Target="https://invalid.example/a"/></Relationships>');await reject(()=>z.generateAsync({type:'uint8array'}).then(R.inspectDoc));await reject(()=>R.xml('<!DOCTYPE x [<!ENTITY a SYSTEM "file:///x">]><x/>'));});
  await test('空白注入不跨越正文及收费条款分段下划线',async()=>{const d=R.xml(`<w:document xmlns:w="${R.W}"><w:p><w:r><w:rPr><w:u w:val="single"/></w:rPr><w:t>前   保留正文   后</w:t></w:r></w:p></w:document>`),para=R.els(d,'p')[0];R.applyRule(para,{mode:'blank_prefix',prefix:'前',suffix:'后',new:'{{PLAINTIFF}}'});eq(R.ptext(para),'前{{PLAINTIFF}}保留正文   后');const out=await R.swapFee(await fixture(p('六、经双方商定，本合同律师费约定如下：')),'semi_risk'),z=await R.openZip(out.bytes),doc=R.xml(await z.file('word/document.xml').async('string'));eq(R.els(doc,'p').length,4);for(const r of R.els(doc,'r'))if(R.els(r,'t').some(t=>t.textContent.includes('{{')))R.assert(R.els(r,'u').some(u=>u.getAttributeNS(R.W,'val')==='single'),'字段缺下划线');});
  await test('目录写入接口保留原目录且写入完整内容',async()=>{function folder(name){return {name,dirs:new Map(),files:new Map(),async getDirectoryHandle(n,o){if(!this.dirs.has(n)){if(!o?.create)throw Object.assign(Error('missing'),{name:'NotFoundError'});this.dirs.set(n,folder(n));}return this.dirs.get(n);},async getFileHandle(n){return {createWritable:async()=>({write:async v=>this.files.set(n,v),close:async()=>{},abort:async()=>{}})};}};}const root=folder('root'),normalized=R.normalize(input);root.dirs.set(normalized.caseName,folder(normalized.caseName));const result={normalized,files:[{name:'样例.docx',bytes:new Uint8Array([1,2,3])}],report:{success:true}},name=await R.saveDirectory(result,root,true);eq(name,normalized.caseName+' (1)');eq(root.dirs.get(normalized.caseName).files.size,0);eq(root.dirs.get(name).dirs.get('01委托手续').files.get('样例.docx').length,3);R.assert(root.dirs.get(name).files.has('生成校验报告.json'),'报告缺失');});
  return {success:checks.every(t=>t.passed),version:R.VERSION,createdAt:new Date().toISOString(),total:checks.length,checks};
 };
})();


