'use strict';
(() => {
 const R=Retainer,$=id=>document.getElementById(id),groups=['个人委托','公司委托','刑事'];
 const names={contract:'委托合同',auth:'授权委托书',legalrep:'法定代表人身份证明',letter:'所函',meeting_letter:'会见信',checklist:'材料清单',extra:'附加文书'};
 const fresh=()=>Object.fromEntries(R.config.fields.map(f=>[f.key,f.options?'自动识别':'']));
 let state={records:[{row:fresh(),sourceRow:null,issues:[]}],index:0,workbook:null,sheet:0,header:1,mapping:{},remember:false,folders:false},result=null,processed=null,sourceFiles=[],rebuilt=[],lastSelftest=null,busy=false,saveTimer=null,saveChain=Promise.resolve();
 const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 const option=(value,label)=>{const o=el('option',label);o.value=value;return o;};
 const notice=(text,error=false)=>{$('notice').hidden=false;$('notice').className=error?'error':'';$('notice').textContent=text;};
 const invalidate=()=>{result=null;$('outputs').hidden=true;};
 const run=fn=>async(...args)=>{if(busy)return;busy=true;const byScan=['scanFile','scanCertType'];const controls=[...document.querySelectorAll('button,input,select,textarea')].filter(e=>!byScan.includes(e.id)).map(e=>[e,e.disabled]);for(const[e]of controls)e.disabled=true;document.body.classList.add('busy');try{await fn(...args);}catch(e){notice(e.message||String(e),true);window.scrollTo({top:0,behavior:'smooth'});}finally{for(const[e,d]of controls)if(e.isConnected)e.disabled=d;busy=false;document.body.classList.remove('busy');$('rebuildSources').disabled=!sourceFiles.length;}};
 const on=(id,fn,event='click')=>$(id).addEventListener(event,run(fn));
 const current=()=>state.records[state.index];
 function snapshot(){return R.clone(state);}
 function scheduleSave(){clearTimeout(saveTimer);if(!state.remember)return;saveTimer=setTimeout(()=>{const s=snapshot();saveChain=saveChain.catch(()=>{}).then(async()=>{try{const data=await R.pack('work',s);await R.storage.put(data);$('storageStatus').textContent='已保存到此浏览器 · '+new Date().toLocaleTimeString();}catch(e){$('storageStatus').textContent='自动保存失败，请下载工作包：'+e.message;}});},500);}
 function showPage(id){for(const p of document.querySelectorAll('.page'))p.hidden=p.id!==id;for(const b of document.querySelectorAll('nav button'))b.classList.toggle('active',b.dataset.page===id);$('pageTitle').textContent=document.querySelector(`[data-page="${id}"]`).textContent;$('notice').hidden=true;}
 for(const b of document.querySelectorAll('nav button'))b.onclick=()=>showPage(b.dataset.page);
 function renderForm(){const form=$('caseForm');form.replaceChildren();for(const f of R.config.fields){const label=el('label',f.label+(['plaintiff','defendant','cause','fee_desc','stage'].includes(f.key)?' *':''));label.dataset.key=f.key;const input=el(f.options?'select':'input');input.id='field_'+f.key;input.name=f.key;
   if(f.options)for(const op of f.options)input.append(option(op,op));input.value=current()?.row[f.key]??'';if(f.options&&input.selectedIndex<0){input.append(option(current().row[f.key],current().row[f.key]));input.value=current().row[f.key];}
   if(f.key==='fee_desc')input.placeholder='例如 50000元，或前期2万+12.5%';if(f.key==='stage')input.placeholder='例如 一审、二审；刑事可填 侦查、审查起诉';
   input.addEventListener('input',()=>{current().row[f.key]=input.value;if(current().invalidFields){delete current().invalidFields[f.key];current().issues=Object.values(current().invalidFields).flat();}invalidate();renderChoices();$('caseCheck').textContent=current().issues?.length?current().issues.join('\n'):'字段已修改，请重新检查。';scheduleSave();});label.append(input);form.append(label);
  }form.onsubmit=e=>e.preventDefault();}
 function renderRecords(){const select=$('caseSelect');select.replaceChildren();state.records.forEach((r,i)=>select.append(option(i,`${i+1}. ${r.row.plaintiff||'未命名案件'}${r.row.defendant?' / '+r.row.defendant:''}${r.sourceRow?'（Excel 第 '+r.sourceRow+' 行）':''}`)));select.value=state.index;$('recordCount').textContent=state.records.length+' 个案件，逐案生成';renderForm();invalidate();$('caseCheck').textContent=current()?.issues?.length?current().issues.join('\n'):'填写后检查，查看识别结果及费用。';}
 function populateGroups(){for(const id of ['generationGroup','templateGroup','maintenanceGroup']){const value=$(id).value;$(id).replaceChildren();if(id==='generationGroup')$(id).append(option('auto','按案件自动选择'));for(const g of groups)$(id).append(option(g,g));if(value)$(id).value=value;}}
 function guessGroup(){try{return R.normalize(current().row).group;}catch{return $('templateGroup').value||'个人委托';}}
 function renderChoices(){const group=$('generationGroup').value==='auto'?guessGroup():$('generationGroup').value,box=$('docChoices');box.replaceChildren();const list=R.templates.filter(x=>x.group===group);const summary=()=>{const s=$('choiceSummary');if(!s)return;const n=box.querySelectorAll('input:checked').length;s.textContent=list.length?('当前模板组「'+group+'」共 '+list.length+' 份，已选 '+n+' 份。'+(group==='个人委托'&&$('generationGroup').value==='auto'?'（案件字段未填全时按默认组显示，填全后自动匹配）':'')):('该模板组没有模板。模板库现有 '+R.templates.length+' 份，请在「模板管理」中检查或恢复内置模板。');};for(const t of list){const label=el('label'),check=el('input');check.type='checkbox';check.checked=true;check.value=t.id;check.onchange=()=>{invalidate();summary();};label.append(check,el('span',t.name));box.append(label);}if(!box.children.length)box.append(el('p','该组没有模板，请先导入或恢复。'));summary();}
 function checkCase(){R.assert(!current().issues?.length,current().issues?.join('\n'));const n=R.normalize(current().row);$('caseCheck').textContent=`类型：${n.case_type==='criminal'?'刑事':'民商事'}　主体：${n.party_type==='company'?'公司':'个人'}　收费：${n.fee_type==='fixed'?'固定':n.fee_type==='pure_risk'?'全风险':'半风险'}\n模板组：${n.group}\n金额：${n.fee_info.upfront}（${n.fee_info.upfront_short}）${n.fee_type!=='fixed'?'\n风险费率：'+n.fee_info.risk_rate:''}`;
  const pv=$('feePreview'),fill=s=>s.replace(/\{\{(\w+)\}\}/g,(m,k)=>n.replacements[k]??m);
  if(n.case_type==='criminal'){pv.hidden=false;pv.textContent='刑事委托合同不使用收费模式注入，其第六条保持模板原样。';}
  else{const cs=R.config.feeClauses[n.fee_type]||[];pv.hidden=false;pv.textContent='合同第六条将写入以下内容（共 '+cs.length+' 段）：\n\n'+cs.map((s,i)=>'【第 '+(i+1)+' 段】'+fill(s)).join('\n\n');}
  return n;}
 function renderMapping(){const sheet=state.workbook?.sheets[state.sheet];if(!sheet)return;const headers=(sheet.rows[state.header-1]||[]).map(c=>c?.value||'');$('mapping').replaceChildren();for(const f of R.config.fields){const label=el('label',f.label),s=el('select');s.dataset.key=f.key;s.append(option('','不映射'));headers.forEach((h,i)=>s.append(option(i,`${R.colName(i)} · ${h||'空表头'}`)));s.value=state.mapping[f.key]??'';s.onchange=()=>{state.mapping[f.key]=s.value;scheduleSave();};label.append(s);$('mapping').append(label);}}
 function loadSheets(){const select=$('sheetSelect');select.replaceChildren();if(state.workbook){state.workbook.sheets.forEach((s,i)=>select.append(option(i,s.name)));select.value=state.sheet;$('headerRow').value=state.header;$('excelControls').hidden=false;renderMapping();}else $('excelControls').hidden=true;}
 function remap(){state.header=Number($('headerRow').value);R.assert(Number.isInteger(state.header)&&state.header>=1,'表头行必须为正整数');const sh=state.workbook.sheets[state.sheet],h=(sh.rows[state.header-1]||[]).map(c=>c?.value||'');R.assert(h.some(Boolean),'选定行没有表头');const m=R.autoMapping(h);state.mapping=m.mapping;$('mapSummary').textContent=m.conflicts.join('；');renderMapping();scheduleSave();}
 on('standardExcel',async()=>R.download(await R.standardXlsx(),'标准案件录入.xlsx'));
 on('excelFile',async()=>{const f=$('excelFile').files[0];if(!f)return;const w=await R.readXlsx(await f.arrayBuffer());state.workbook=w;state.sheet=0;state.header=Math.max(1,w.sheets[0].rows.findIndex(r=>r?.some(c=>c?.value))+1);loadSheets();remap();notice('已读取 '+f.name+'，请核对映射后点击“应用映射并读取案件”。');},'change');
 on('sheetSelect',()=>{state.sheet=Number($('sheetSelect').value);state.header=Math.max(1,state.workbook.sheets[state.sheet].rows.findIndex(r=>r?.some(c=>c?.value))+1);$('headerRow').value=state.header;remap();},'change');on('remap',remap);
 on('applyMapping',()=>{const records=R.mapRows(state.workbook.sheets[state.sheet],state.header-1,state.mapping);R.assert(records.length,'映射后没有案件数据');state.records=records;state.index=0;renderRecords();renderChoices();scheduleSave();notice('已读取 '+records.length+' 个案件。请选择一案核对。');});
 on('newCase',()=>{state.records.push({row:fresh(),sourceRow:null,issues:[]});state.index=state.records.length-1;renderRecords();renderChoices();scheduleSave();});
 on('deleteCase',()=>{state.records.splice(state.index,1);if(!state.records.length)state.records=[{row:fresh(),sourceRow:null,issues:[]}];state.index=Math.min(state.index,state.records.length-1);renderRecords();renderChoices();scheduleSave();});
 on('caseSelect',()=>{state.index=Number($('caseSelect').value);renderRecords();renderChoices();scheduleSave();},'change');
 on('checkCase',()=>{checkCase();renderChoices();notice('当前案件字段检查通过。');});
 on('generationGroup',()=>{invalidate();renderChoices();},'change');
 on('includeFolders',()=>{state.folders=$('includeFolders').checked;scheduleSave();},'change');
 on('generate',async()=>{const n=checkCase(),selected=[...$('docChoices').querySelectorAll('input:checked')].map(i=>i.value),ts=R.templates.filter(t=>selected.includes(t.id));R.assert(ts.every(t=>t.group===n.group),'所选模板组与案件类型/收费方式不一致，请调整案件字段或模板组');result=await R.generate(n,ts);$('outputFiles').replaceChildren();for(const f of result.files){const b=el('button',f.name);b.onclick=()=>R.download(f.bytes,f.name);$('outputFiles').append(b);}$('outputs').hidden=false;notice(`已生成 ${result.files.length} 份文书，字段与文档结构校验通过。`);});
 on('downloadZip',async()=>{R.assert(result,'请先生成');R.download(await R.caseZip(result,$('includeFolders').checked),result.normalized.caseName+'.zip');});
 on('downloadReport',()=>{R.assert(result,'请先生成');R.download(JSON.stringify(result.report,null,2),'生成校验报告.json','application/json');});
 on('saveFolder',async()=>{R.assert(result,'请先生成');if(!window.showDirectoryPicker){R.download(await R.caseZip(result,$('includeFolders').checked),result.normalized.caseName+'.zip');notice('此浏览器不支持目录写入，已改为下载完整 ZIP。');return;}const root=await window.showDirectoryPicker({mode:'readwrite'});notice('已保存至 '+await R.saveDirectory(result,root,$('includeFolders').checked));});
 function renderTemplates(){const table=el('table'),head=el('tr');for(const s of ['文书','状态','操作'])head.append(el('th',s));table.append(head);for(const t of R.templates.filter(x=>x.group===$('templateGroup').value)){const tr=el('tr'),name=el('td',t.name),status=el('td',t.builtin?'内置':'工作副本'),buttons=el('td'),acts=el('div',undefined,'actions');
   const down=el('button','下载'),inspect=el('button','检查字段'),restore=el('button','恢复/移除');down.onclick=()=>R.download(R.bytes(t.base64),t.name);inspect.onclick=run(async()=>{const info=await R.validateTemplate(t);$('templateReport').hidden=false;$('templateReport').textContent=JSON.stringify({name:t.name,fields:info.fields,locations:info.locations},null,2);});restore.onclick=run(()=>{const b=RETAINER_BUILTIN.templates.find(x=>x.id===t.id);R.templates=R.templates.filter(x=>x.id!==t.id);if(b)R.templates.push(R.clone(b));renderTemplates();renderChoices();invalidate();scheduleSave();});acts.append(down,inspect,restore);buttons.append(acts);tr.append(name,status,buttons);table.append(tr);}$('templateList').replaceChildren(table);}
 async function makeTemplate(b,name,group,tag){const builtin=RETAINER_BUILTIN.templates.find(t=>t.group===group&&t.tag===tag);return {id:builtin?.id||group+'/'+R.safeName(name),name:builtin?.name||R.safeName(name),group,tag,base64:R.base64(b),sha256:await R.hash(b),builtin:false};}
 function adopt(ts){for(const t of ts){R.templates=R.templates.filter(x=>x.id!==t.id);R.templates.push(t);}renderTemplates();renderChoices();invalidate();scheduleSave();}
 on('templateGroup',renderTemplates,'change');
 on('templateFile',async()=>{const f=$('templateFile').files[0];if(!f)return;const t=await makeTemplate(new Uint8Array(await f.arrayBuffer()),f.name,$('templateGroup').value,$('importTag').value);await R.validateTemplate(t);adopt([t]);notice('已校验并导入 '+t.name);$('templateFile').value='';},'change');
 async function integrity(){const errors=[],details=[];for(const b of RETAINER_BUILTIN.templates)if(!R.templates.some(t=>t.id===b.id))errors.push('缺少：'+b.id);for(const t of R.templates){try{await R.validateTemplate(t);details.push(t.id+'：通过');}catch(e){errors.push(t.id+'：'+e.message);}}return {success:!errors.length,errors,details};}
 on('verifyTemplates',async()=>{$('templateReport').hidden=false;$('templateReport').textContent=JSON.stringify(await integrity(),null,2);});
 on('restoreAll',()=>{R.templates=R.clone(RETAINER_BUILTIN.templates);renderTemplates();renderChoices();invalidate();scheduleSave();notice('已恢复全部内置模板（'+R.templates.length+' 份）。');});
 async function maintenance(action){const file=$('maintenanceFile').files[0];R.assert(file,'请先选择待处理 DOCX');const data=new Uint8Array(await file.arrayBuffer()),group=$('maintenanceGroup').value,tag=$('maintenanceTag').value;
  if(action==='fixed'||action==='semi_risk'||action==='pure_risk')R.assert(group!=='刑事'&&tag==='contract','收费条款转换仅用于民事委托合同');
  const out=action==='clean'?await R.clean(data):action==='inject'?await R.inject(data,group,tag):await R.swapFee(data,action);
  const targetGroup=group;
  processed={...out,name:file.name,group:targetGroup,tag};$('maintenanceResult').hidden=false;$('maintenanceReport').textContent=JSON.stringify({targetGroup,changes:out.report},null,2);notice('已生成处理副本，目标组为 '+targetGroup+'。请核对报告，原文件未修改。');
 }
 on('cleanTemplate',()=>maintenance('clean'));on('injectTemplate',()=>maintenance('inject'));on('feeFixed',()=>maintenance('fixed'));on('feeRisk',()=>maintenance('semi_risk'));on('feePure',()=>maintenance('pure_risk'));
 on('downloadMaintenance',()=>{R.assert(processed,'请先处理文件');R.download(processed.bytes,'处理后-'+processed.name);});on('downloadMaintenanceReport',()=>{R.assert(processed,'请先处理文件');R.download(JSON.stringify(processed.report,null,2),'模板处理报告.json');});
 on('adoptMaintenance',async()=>{R.assert(processed,'请先处理文件');const t=await makeTemplate(processed.bytes,processed.name,processed.group,processed.tag);await R.validateTemplate(t);adopt([t]);notice('处理副本已采纳为工作模板。');});
 function sourceMap(files){sourceFiles=[...files].filter(f=>/\.docx$/i.test(f.name));R.assert(sourceFiles.length&&sourceFiles.length<=100,'请选择 1 至 100 个 DOCX');rebuilt=[];$('rebuildResult').hidden=true;const table=el('table',undefined,'source-map'),head=el('tr');for(const s of ['使用','源文件','模板组','类型'])head.append(el('th',s));table.append(head);
  sourceFiles.forEach((f,i)=>{const tr=el('tr'),check=el('input');check.type='checkbox';check.checked=true;check.dataset.source=i;const ctd=el('td');ctd.append(check);const gs=el('select'),ts=el('select');gs.dataset.group=i;ts.dataset.tag=i;for(const g of groups)gs.append(option(g,g));for(const [k,v] of Object.entries(names))if(k!=='extra')ts.append(option(k,v));const path=f.webkitRelativePath||f.name;gs.value=path.includes('刑事')?'刑事':(path.includes('公司')?'公司委托':'个人委托');ts.value=f.name.includes('合同')?'contract':f.name.includes('授权')?'auth':f.name.includes('身份证明')?'legalrep':f.name.includes('会见')?'meeting_letter':f.name.includes('所函')?'letter':'checklist';const gd=el('td'),td=el('td');gd.append(gs);td.append(ts);tr.append(ctd,el('td',path),gd,td);table.append(tr);});$('sourceMappings').replaceChildren(table);$('rebuildSources').disabled=false;}
 on('sourceFiles',()=>sourceMap($('sourceFiles').files),'change');on('sourceDirectory',()=>sourceMap($('sourceDirectory').files),'change');
 on('rebuildSources',async()=>{const report=[],candidates=[],ids=new Set();for(const check of $('sourceMappings').querySelectorAll('input:checked')){const i=Number(check.dataset.source),f=sourceFiles[i],group=$('sourceMappings').querySelector(`[data-group="${i}"]`).value,tag=$('sourceMappings').querySelector(`[data-tag="${i}"]`).value;
   try{const out=await R.inject(new Uint8Array(await f.arrayBuffer()),group,tag),t=await makeTemplate(out.bytes,f.name,group,tag);await R.validateTemplate(t);R.assert(!ids.has(t.id),'多个源文件对应同一目标文书');ids.add(t.id);candidates.push(t);report.push({file:f.name,target:t.id,success:true,details:out.report});}catch(e){report.push({file:f.name,success:false,error:e.message});}}
   R.assert(report.length,'请选择源文件');rebuilt=candidates;$('rebuildResult').hidden=false;$('rebuildReport').textContent=JSON.stringify({files:report,missing:RETAINER_BUILTIN.templates.filter(t=>!ids.has(t.id)).map(t=>t.id)},null,2);notice(`已处理 ${report.length} 份，通过 ${candidates.length} 份；请查看缺失与失败清单。`);
 });
 on('downloadRebuilt',async()=>{R.assert(rebuilt.length,'尚无已通过模板');const z=new JSZip();for(const t of rebuilt)z.file(t.id,R.bytes(t.base64));z.file('重建报告.json',$('rebuildReport').textContent);R.download(await z.generateAsync({type:'uint8array',compression:'DEFLATE'}),'重建模板.zip');});on('adoptRebuilt',()=>{R.assert(rebuilt.length,'尚无已通过模板');adopt(rebuilt);notice('已采纳 '+rebuilt.length+' 份模板，其余工作模板保留。');});
 on('exportWork',async()=>R.download(await R.pack('work',snapshot()),'委托材料工作包.zip'));on('exportResources',async()=>R.download(await R.pack('resources'),'委托材料资源包.zip'));
 function refresh(){populateGroups();renderRecords();renderChoices();renderTemplates();loadSheets();$('remember').checked=state.remember;$('includeFolders').checked=state.folders;}
 async function importPack(id,kind){const f=$(id).files[0];if(!f)return;const p=await R.unpack(await f.arrayBuffer(),kind);if(kind==='work'){clearTimeout(saveTimer);await saveChain.catch(()=>{});await R.storage.clear().catch(()=>{});}R.applyPackage(p);if(kind==='work'){state=p.state;state.index=Math.max(0,Math.min(state.index||0,state.records.length-1));if(!state.records.length){state.records=[{row:fresh(),issues:[]}];state.index=0;}state.remember=false;$('storageStatus').textContent='工作包已恢复；自动保存关闭。';}refresh();scheduleSave();notice(p.importedFrom?('已从 '+p.importedFrom+' 版工作包导入案件数据；模板与收费条款已改用本版内置资源，请核对后使用。'):('已恢复本地'+(kind==='work'?'工作包；自动保存保持关闭。':'资源包。')));$(id).value='';}
 on('importWork',()=>importPack('importWork','work'),'change');on('importResources',()=>importPack('importResources','resources'),'change');
 on('remember',async()=>{state.remember=$('remember').checked;if(state.remember){try{await R.storage.put(await R.pack('work',snapshot()));$('storageStatus').textContent='已开启，工作内容将自动保存到此浏览器。';}catch(e){state.remember=false;$('remember').checked=false;$('storageStatus').textContent='保存失败，请下载工作包：'+e.message;throw e;}}else{clearTimeout(saveTimer);await saveChain.catch(()=>{});await R.storage.clear();$('storageStatus').textContent='已关闭自动保存并移除浏览器副本，当前页面数据仍在内存。';}},'change');
 on('clearStorage',async()=>{clearTimeout(saveTimer);state.remember=false;$('remember').checked=false;await saveChain.catch(()=>{});await R.storage.clear();$('storageStatus').textContent='浏览器保存内容已清除；当前页面数据仍在内存。';});
 on('loadConfigEditor',()=>{$('configEditor').value=JSON.stringify({config:R.config,rules:R.rules},null,2);});on('applyConfigEditor',()=>{const p=JSON.parse($('configEditor').value);R.validateConfig(p.config,p.rules);R.config=R.clone(p.config);R.rules=R.clone(p.rules);refresh();scheduleSave();notice('规则配置已校验并应用；模板中的固定文字未被改写。');});on('resetConfig',()=>{R.config=R.clone(RETAINER_CONFIG);R.rules=R.clone(RETAINER_RULES);refresh();scheduleSave();notice('已恢复内置规则配置。');});
 const guide=`使用流程\n\n1. 下载标准 Excel，在“案件录入”每行填写一个案件；也可直接新建案件填写。\n2. 导入 Excel，选择工作表和表头行，核对字段映射后读取案件。\n3. 选择一案，核对金额、阶段及模板组，生成 Word。\n4. 下载单份文书或当前案件 ZIP。“包含完整案件目录”会保留原技能全部目录。\n\n模板管理\n内置三类共13份模板（个人委托 / 公司委托 / 刑事）。导入带占位符的自定义 Word 可替换同组文书；附加文书按文件名添加。源模板先在“模板处理工具”注入，查看报告后采纳。清理仅合并相邻同格式纯文字，不删除图片或字段。收费条款转换仅用于民事合同，生成副本供核对。\n\n本地保存\n默认不留存。可主动开启自动记住；也可下载工作包备份和迁移。工作包为普通本地文件，不含加密。浏览器存储不可用时请使用工作包。资源包不包含案件数据。\n\n输入支持与限制\n现有案件字段、固定 / 半风险 / 全风险收费。金额示例：50000元、2.5万元（固定）；前期2万+12.5%（半风险）；回款额的15%（全风险）。多金额、分期、结果收费需要另行处理合同，本程序会报错。Excel 不计算公式；先粘贴为值。\n\n安全与离线\n本工具不连接网络。导入文件中的宏、活动内容、外部资源引用不被执行，含这些内容的文件会被拒绝。原桌面源模板未随技能提供，重建需手动选择源文件；恢复内置模板无需源文件。\n\n版式与签署\n保留模板的格式结构，文字变长仍可能影响分页。在 Word 中复核排版、代理权限及签署信息，填写日期和合同编号。默认律师、账户等来自原模板，不属于 Excel 录入字段。\n\n维护数据\ndata/config.json 与 data/rules.json 为可读配置；运行加载对应本地 .js 数据文件。普通维护请使用资源包及高级配置编辑，维护者修改 JSON 后使用 tools/build.go 重新生成加载文件。\n\n完整性\n“检查完整性”核对模板缺失、哈希与字段；“离线自检”使用虚构样例验证运行能力。原技能源码与说明在本页下拉框及 original-skill 目录完整保留。`;
 const docs={'使用说明':guide,'能力迁移对照':`案件输入 → 案件表单 / Excel 字段映射\n类型识别与金额 → 检查字段\n文书生成 → 生成当前案件文书\n案件目录 / 归档 → 包含完整案件目录 / 保存到本地目录\n模板完整性 / 恢复 → 模板管理\n占位符注入 / 下划线处理 → 模板处理工具\n模板清理 → 合并同格式文字片段\n收费条款转换 → 固定 / 半风险 / 全风险副本\n源模板重建 → 从源模板重建\n规则与默认信息 → 保存与资源 / 高级数据维护\n结果 JSON / 校验 → 校验报告\n版本 / 测试 → 说明与自检\n全部原技能文件 → original-skill 与本页完整资料`,...RETAINER_BUILTIN.originalDocs,...RETAINER_BUILTIN.appDocs};
 for(const k of Object.keys(docs))$('helpSelect').append(option(k,k));$('helpContent').textContent=guide;$('helpSelect').onchange=()=>{$('helpContent').textContent=docs[$('helpSelect').value];};
 const pt=el('table');for(const [k,v]of Object.entries(R.config.placeholders)){const tr=el('tr');tr.append(el('td','{{'+k+'}}'),el('td',v));pt.append(tr);}$('placeholderTable').append(pt);
 on('selftest',async()=>{$('selftestReport').textContent='正在使用虚构案件运行自检…';lastSelftest=await R.selftest();$('selftestReport').textContent=JSON.stringify(lastSelftest,null,2);notice(lastSelftest.success?'自检通过。':'自检发现失败项，请查看报告。',!lastSelftest.success);});on('downloadSelftest',()=>{R.assert(lastSelftest,'请先运行自检');R.download(JSON.stringify(lastSelftest,null,2),'离线自检报告.json');});
 refresh();window.RETAINER_UI={getState:snapshot,setState:s=>{state=s;refresh();},getResult:()=>result,integrity};
 (async()=>{try{const saved=await R.storage.get();if(saved){const p=await R.unpack(saved,'work');if(p.state.remember){R.applyPackage(p);state=p.state;refresh();$('storageStatus').textContent=p.importedFrom?('已从 '+p.importedFrom+' 版保存内容恢复案件数据；模板已升级为本版。'):'已恢复此浏览器保存的工作内容。';notice(p.importedFrom?'已从旧版保存内容恢复案件数据，模板与收费条款已升级为本版。':'已恢复上次保存的工作内容。');}}}catch(e){$('storageStatus').textContent='浏览器保存不可用或恢复失败，请导入工作包：'+e.message;}})();
})();

